// Centiform manifest: the single source of truth for the gallery.
// One entry per design, in number order. Registry: blueprint section 4.
// A design folder is designs/<slug>/index.html. status is "planned" or "done".
window.CENTIFORM = [
  { n: 1, slug: "001-kodachrome-lightbox", title: "Kodachrome Lightbox", family: "Paper & Print",
    subject: "A family travel-slide archive, 1958-1971.", format: "catalog", mode: "light",
    thesis: "1960s 35mm slides laid on a glowing lightbox, labelled in grease pencil",
    fonts: ["Cutive Mono","Caveat"], swatch: ["#efe9da","#2a211b","#c8231b","#f0b323"],
    grammar: "Loose grid of 2-inch cardboard mounts on a backlit table; a loupe follows the cursor",
    motif: "Stamped cardboard slide mount with processing date",
    status: "done" },
  { n: 2, slug: "002-alpine-timetable", title: "Alpine Timetable", family: "Paper & Print",
    subject: "Departure timetable for a fictional mountain rail line.", format: "tool", mode: "light",
    thesis: "Swiss International Style: flush-left, objective, one red",
    fonts: ["Instrument Sans","Red Hat Mono"], swatch: ["#ffffff","#0b0b0b","#e2001a","#9b9b9b"],
    grammar: "Strict 12-column grid, all text flush-left, tabular figures, hairline rules only",
    motif: "Station clock with a red disc seconds hand that pauses at the top",
    status: "done" },
  { n: 3, slug: "003-riso-repair-zine", title: "Riso Repair Zine", family: "Paper & Print",
    subject: "Zine for a community bike-repair collective.", format: "editorial", mode: "light",
    thesis: "Two-drum risograph print with misregistration and overprint",
    fonts: ["Rubik Mono One","Rubik"], swatch: ["#f3efe6","#0078bf","#ff48b0","#1d1d1d"],
    grammar: "Stapled spreads, blocks offset 2-4px between the two ink layers, mix-blend-mode multiply",
    motif: "Halftone dot fills and the purple where pink overprints blue",
    status: "done" },
  { n: 4, slug: "004-exposition-broadsheet", title: "Exposition Broadsheet", family: "Paper & Print",
    subject: "Front page covering a fictional 1893 industrial exposition.", format: "editorial", mode: "light",
    thesis: "Victorian newspaper: seven dense justified columns",
    fonts: ["UnifrakturMaguntia","Old Standard TT"], swatch: ["#e9e0cb","#1b1814","#7a1f1f","#8a7f6a"],
    grammar: "Seven columns with vertical hairline rules, stacked decks of headlines, no whitespace",
    motif: "Engraved dingbats and a blackletter masthead with ornamental rules",
    status: "done" },
  { n: 5, slug: "005-triband-paperbacks", title: "Tri-Band Paperbacks", family: "Paper & Print",
    subject: "Backlist of a fictional mid-century paperback imprint.", format: "catalog", mode: "light",
    thesis: "Horizontal three-band book covers; colour codes the genre",
    fonts: ["Josefin Sans","Crimson Pro"], swatch: ["#f4efe1","#1d1d1b","#e8702a","#2d7d46"],
    grammar: "A shelf of spines that pull out into full tri-band covers",
    motif: "Three horizontal bands with a centred cartouche",
    status: "done" },
  { n: 6, slug: "006-herbarium-sheets", title: "Herbarium Sheets", family: "Paper & Print",
    subject: "Accession records of a university herbarium.", format: "catalog", mode: "light",
    thesis: "Pressed plants on rag paper with typed labels and linen tape",
    fonts: ["Cormorant","Sometype Mono"], swatch: ["#ece4cf","#3b4a2a","#7b4a2e","#b8872b"],
    grammar: "One specimen sheet per view, label block fixed bottom-right, pencil notes in margins",
    motif: "Linen tape strips and accession-number stamps",
    status: "done" },
  { n: 7, slug: "007-transit-annual-1972", title: "Transit Annual 1972", family: "Paper & Print",
    subject: "Annual report of a fictional regional transit authority.", format: "editorial", mode: "light",
    thesis: "1972 corporate modernism: heavy black band, big numerals, modular grid",
    fonts: ["Work Sans","Spectral"], swatch: ["#eceae4","#1a1a1a","#7a2e8e","#d9b310"],
    grammar: "Thick black top band on every spread, 6-unit modular grid, figures set huge",
    motif: "Oversized financial numerals with thin unit labels",
    status: "done" },
  { n: 8, slug: "008-basement-xerox", title: "Basement Xerox", family: "Paper & Print",
    subject: "Flyer wall for a basement show series.", format: "poster", mode: "light",
    thesis: "Punk cut-and-paste collage, photocopied",
    fonts: ["Anton","Special Elite"], swatch: ["#d9d9d4","#0d0d0d","#e8ff3a","#ff3b1f"],
    grammar: "Rotated, overlapping fragments with no grid; content held together by tape",
    motif: "Torn paper edges (clip-path) and ransom-note letters",
    status: "done" },
  { n: 9, slug: "009-farmers-almanac", title: "Farmer's Almanac", family: "Paper & Print",
    subject: "Planting calendar and moon-phase tables for one year.", format: "tool", mode: "light",
    thesis: "19th-century almanac: dense tables, woodcuts, red and black ink",
    fonts: ["Sorts Mill Goudy","Alegreya SC"], swatch: ["#f1e6c8","#2b2118","#a33b20","#5b6b3a"],
    grammar: "Month tables with ruled rows, woodcut sun and moon in headers",
    motif: "Rows of moon-phase glyphs drawn in SVG",
    status: "done" },
  { n: 10, slug: "010-museum-wall-label", title: "Museum Wall Label", family: "Paper & Print",
    subject: "A single-object museum exhibition.", format: "landing", mode: "light",
    thesis: "Gallery minimalism: one object, a lot of wall, one tombstone label",
    fonts: ["Newsreader","Karla"], swatch: ["#f7f6f2","#222222","#3d5a73","#c9c4b8"],
    grammar: "One object per full screen, label at eye level lower-left, 80% empty wall",
    motif: "Tombstone label (artist, date, medium, accession)",
    status: "done" },
  { n: 11, slug: "011-phosphor-scope", title: "Phosphor Scope", family: "Instruments",
    subject: "Product page for a modular synth oscillator.", format: "app", mode: "dark",
    thesis: "Analogue oscilloscope: P31 green phosphor, graticule, persistence",
    fonts: ["Share Tech Mono","Chakra Petch"], swatch: ["#0a0f0a","#6aff8f","#1c3a22","#ffb000"],
    grammar: "Bezel frame with knob controls, 10x8 graticule, live SVG waveform",
    motif: "Phosphor glow with fading persistence trails",
    status: "done" },
  { n: 12, slug: "012-pocket-calculator-manual", title: "Pocket Calculator Manual", family: "Instruments",
    subject: "Owner's manual for a fictional 1983 pocket calculator.", format: "docs", mode: "light",
    thesis: "Japanese electronics manual: device drawing with numbered callouts",
    fonts: ["DotGothic16","M PLUS 1p"], swatch: ["#e9e6df","#2b2b2b","#e4572e","#8a9a7b"],
    grammar: "Device illustration at centre, leader lines to keys, numbered steps",
    motif: "CSS seven-segment LCD digits on a grey-green display",
    status: "done" },
  { n: 13, slug: "013-glass-cockpit", title: "Glass Cockpit", family: "Instruments",
    subject: "Training module for a fictional regional airliner.", format: "dashboard", mode: "dark",
    thesis: "1980s EFIS symbology: magenta, cyan, green on black",
    fonts: ["B612","B612 Mono"], swatch: ["#000000","#3df2ff","#ff3df2","#3dff5a"],
    grammar: "Primary flight display and navigation display as the two main tiles",
    motif: "Attitude indicator horizon that tilts on scroll",
    status: "done" },
  { n: 14, slug: "014-valve-radio-dial", title: "Valve Radio Dial", family: "Instruments",
    subject: "A radio-drama archive.", format: "landing", mode: "dark",
    thesis: "1950s valve radio: bakelite case, glowing dial glass",
    fonts: ["Limelight","Marcellus"], swatch: ["#3e2417","#e8d49a","#b23a1c","#c9a14a"],
    grammar: "Horizontal tuning dial is the navigation; each station is a section",
    motif: "Tuning needle that slides between city names",
    status: "done" },
  { n: 15, slug: "015-card-catalog", title: "Card Catalog", family: "Instruments",
    subject: "Search interface for a small-town library.", format: "tool", mode: "light",
    thesis: "Oak card-catalogue drawers and typed index cards",
    fonts: ["Anonymous Pro","Libre Baskerville"], swatch: ["#c89b6d","#2e1f14","#fbf8ef","#b33a3a"],
    grammar: "Drawers with brass label holders open into stacks of index cards",
    motif: "Typed 3x5 card with punch hole and red top rule",
    status: "planned" },
  { n: 16, slug: "016-split-flap-departures", title: "Split-Flap Departures", family: "Instruments",
    subject: "Departure board for a fictional night-train terminal.", format: "dashboard", mode: "dark",
    thesis: "Mechanical split-flap board with flipping characters",
    fonts: ["Barlow Condensed","Barlow"], swatch: ["#1b1b1d","#f2f2f0","#ffcf3f","#2f2f33"],
    grammar: "Rows of flap cells; every value is spelled out cell by cell",
    motif: "Flip animation per character (CSS 3D rotateX)",
    status: "planned" },
  { n: 17, slug: "017-punch-card-batch", title: "Punch Card Batch", family: "Instruments",
    subject: "Job control documentation for a fictional 1968 mainframe.", format: "docs", mode: "light",
    thesis: "80-column punch cards and line-printer greenbar",
    fonts: ["IBM Plex Mono","IBM Plex Sans"], swatch: ["#f0e7c6","#1f2a44","#c6d9b8","#d23c2a"],
    grammar: "Content set on 80-column cards; output pages on greenbar paper",
    motif: "Punched rectangles that encode each heading",
    status: "planned" },
  { n: 18, slug: "018-four-shade-handheld", title: "Four-Shade Handheld", family: "Instruments",
    subject: "Guide to a fictional handheld game.", format: "app", mode: "light",
    thesis: "160x144 pixel screen, exactly four shades of green",
    fonts: ["Press Start 2P","Pixelify Sans"], swatch: ["#9bbc0f","#0f380f","#306230","#8bac0f"],
    grammar: "All content rendered on a scaled 160x144 canvas-like grid; image-rendering pixelated",
    motif: "Dot-matrix screen bezel with a power LED",
    status: "planned" },
  { n: 19, slug: "019-hifi-brochure-1965", title: "Hi-Fi Brochure 1965", family: "Instruments",
    subject: "Launch brochure for a fictional record player.", format: "landing", mode: "light",
    thesis: "West German industrial design: grey, one orange control, strict order",
    fonts: ["Jost","Chivo Mono"], swatch: ["#e4e2dd","#3a3a38","#f25c05","#b9b6ae"],
    grammar: "Product at 1:1 scale drawing, specs in a rigid two-column table",
    motif: "Circular speaker perforation grid",
    status: "planned" },
  { n: 20, slug: "020-darkroom-contact-sheet", title: "Darkroom Contact Sheet", family: "Instruments",
    subject: "Portfolio of a documentary photographer.", format: "catalog", mode: "dark",
    thesis: "Red safelight darkroom: contact sheets, grease-pencil crop marks",
    fonts: ["Syncopate","Fragment Mono"], swatch: ["#1a0503","#ff3a1f","#f3e9dc","#5c1a10"],
    grammar: "Film strips of 36 frames, selected frames circled",
    motif: "Film-edge codes and frame numbers along each strip",
    status: "planned" },
  { n: 21, slug: "021-beton-brut", title: "Beton Brut", family: "Architecture",
    subject: "A fictional civic concert hall.", format: "landing", mode: "light",
    thesis: "Brutalist architecture: board-formed concrete, deep shadows, mass",
    fonts: ["Big Shoulders Display","Public Sans"], swatch: ["#b9b6b0","#262626","#8c8a85","#d94f30"],
    grammar: "Huge cantilevered blocks, cutout windows reveal content, no rounded corners",
    motif: "Board-formed concrete texture (SVG noise and grain lines)",
    status: "planned" },
  { n: 22, slug: "022-cyanotype-blueprint", title: "Cyanotype Blueprint", family: "Architecture",
    subject: "Construction drawings for a fictional lighthouse.", format: "docs", mode: "dark",
    thesis: "Architectural blueprint: white line on cyanotype blue",
    fonts: ["Architects Daughter","Sono"], swatch: ["#12426b","#eaf2f8","#8fb4d1","#f5d76e"],
    grammar: "Drawing sheet with title block, section and elevation views, dimension lines",
    motif: "Dimension lines with arrowheads and revision clouds",
    status: "planned" },
  { n: 23, slug: "023-tatami-ma", title: "Tatami Ma", family: "Architecture",
    subject: "A fictional ryokan (inn).", format: "landing", mode: "light",
    thesis: "Japanese interior: tatami module, shoji grid, emptiness",
    fonts: ["Shippori Mincho","Zen Kaku Gothic New"], swatch: ["#ede3cc","#2f2a24","#6f7d4a","#a6402b"],
    grammar: "Layout built from 1:2 tatami rectangles; vertical text in places",
    motif: "Shoji lattice that slides open to show sections",
    status: "planned" },
  { n: 24, slug: "024-deco-elevator-lobby", title: "Deco Elevator Lobby", family: "Architecture",
    subject: "A fictional 1930 skyscraper's tenant directory.", format: "landing", mode: "dark",
    thesis: "Art Deco lobby: gold sunbursts, black marble, elevator doors",
    fonts: ["Poiret One","Tenor Sans"], swatch: ["#0f0f0f","#d4af6a","#1f4b3f","#efe6d2"],
    grammar: "Strong vertical symmetry, stepped ziggurat frames",
    motif: "Elevator floor-indicator arc that shows scroll progress",
    status: "planned" },
  { n: 25, slug: "025-palm-springs-breeze", title: "Palm Springs Breeze", family: "Architecture",
    subject: "Rental of a fictional mid-century desert house.", format: "landing", mode: "light",
    thesis: "Desert modernism: breeze blocks, pool turquoise, long low lines",
    fonts: ["Righteous","Questrial"], swatch: ["#f6ead2","#3a2e2a","#2fb8b3","#f2a03d"],
    grammar: "Long horizontal bands, strong cast shadows at a 30 degree sun angle",
    motif: "Breeze-block screen pattern (CSS masks)",
    status: "planned" },
  { n: 26, slug: "026-rose-window", title: "Rose Window", family: "Architecture",
    subject: "Restoration campaign for a Gothic cathedral window.", format: "poster", mode: "dark",
    thesis: "Stained glass: lead cames, jewel colours, radial symmetry",
    fonts: ["Uncial Antiqua","Cardo"], swatch: ["#101018","#b0182a","#1d4ea8","#e8b923"],
    grammar: "Radial layout; content in petals of a 12-fold rose",
    motif: "Lead lines that cast coloured light onto the page",
    status: "planned" },
  { n: 27, slug: "027-mosaic-bus-stop", title: "Mosaic Bus Stop", family: "Architecture",
    subject: "Field guide to fictional Soviet-era modernist bus stops.", format: "catalog", mode: "light",
    thesis: "Soviet modernism: smalti mosaic, sculptural concrete shells",
    fonts: ["Ruslan Display","PT Sans"], swatch: ["#e6ddd0","#2c2c2c","#c8412b","#2e7d8c"],
    grammar: "Each stop is a sculptural silhouette card; mosaic panels as section headers",
    motif: "Smalti mosaic tessellation (SVG Voronoi, hand-tuned)",
    status: "planned" },
  { n: 28, slug: "028-subway-tile-station", title: "Subway Tile Station", family: "Architecture",
    subject: "Station information for a fictional metro line.", format: "tool", mode: "light",
    thesis: "Early subway stations: white tile, mosaic name tablets, bands",
    fonts: ["Arvo","Hind"], swatch: ["#f4f4ef","#1d3b2a","#b8862f","#8a3324"],
    grammar: "Everything sits on a 3x6 tile grid with grout lines",
    motif: "Mosaic name tablet with a border band",
    status: "planned" },
  { n: 29, slug: "029-isometric-planner", title: "Isometric Planner", family: "Architecture",
    subject: "A city-planning simulation budget screen.", format: "app", mode: "light",
    thesis: "Isometric city-builder: 2:1 isometric tiles, zoning colours",
    fonts: ["Bungee","Sen"], swatch: ["#cfe3a8","#2d2a32","#4d8fd1","#e6b422"],
    grammar: "Isometric board fills the screen; panels are toolbars",
    motif: "Zoning colours (residential, commercial, industrial) as UI accents",
    status: "planned" },
  { n: 30, slug: "030-victorian-glasshouse", title: "Victorian Glasshouse", family: "Architecture",
    subject: "A fictional botanical conservatory reopening.", format: "landing", mode: "light",
    thesis: "Iron and glass conservatory: arched ribs, condensation, palms",
    fonts: ["Italiana","Gelasio"], swatch: ["#e3ece6","#23332b","#7fa38a","#c9b27c"],
    grammar: "Arched iron ribs frame each section; page scrolls up through the dome",
    motif: "Fogged glass (backdrop-filter) with drip trails",
    status: "planned" },
  { n: 31, slug: "031-zellige-riad", title: "Zellige Riad", family: "Crafts",
    subject: "A fictional riad guesthouse in Fes.", format: "landing", mode: "light",
    thesis: "Moroccan zellige: hand-cut glazed tile, 8-fold star geometry",
    fonts: ["Aref Ruqaa","Amiri"], swatch: ["#f3efe4","#1f3b2d","#c98a2b","#2b2b2b"],
    grammar: "Content framed by tiled borders; the central courtyard is the hero",
    motif: "8-fold star tessellation built in SVG with glaze variation",
    status: "planned" },
  { n: 32, slug: "032-boro-indigo", title: "Boro Indigo", family: "Crafts",
    subject: "A fictional textile-repair studio.", format: "catalog", mode: "dark",
    thesis: "Japanese boro: patched, faded indigo cotton with sashiko stitch",
    fonts: ["Yuji Syuku","Zen Old Mincho"], swatch: ["#1c2a44","#e8e2d4","#3b5a8c","#c24d2c"],
    grammar: "Irregular patchwork panels of different indigo depths",
    motif: "Running-stitch lines (dashed SVG strokes) joining patches",
    status: "planned" },
  { n: 33, slug: "033-papel-picado", title: "Papel Picado", family: "Crafts",
    subject: "A neighbourhood fiesta programme.", format: "poster", mode: "light",
    thesis: "Mexican cut-tissue banners on strings",
    fonts: ["Lilita One","Asap"], swatch: ["#fff8ec","#e6007e","#ffb400","#00a19a"],
    grammar: "Banners hang across the top and sway; programme below in cards",
    motif: "Cut-paper banner with punched motifs (CSS mask)",
    status: "planned" },
  { n: 34, slug: "034-bagru-block-print", title: "Bagru Block Print", family: "Crafts",
    subject: "A fictional hand-block-printed textile co-op.", format: "catalog", mode: "light",
    thesis: "Rajasthani hand block printing: natural dyes on unbleached cotton",
    fonts: ["Yatra One","Martel"], swatch: ["#f3d9b1","#2a1f1a","#a8322d","#2f4f7a"],
    grammar: "Repeat patterns with visible block registration; swatch cards",
    motif: "Carved wooden block that stamps the pattern on hover",
    status: "planned" },
  { n: 35, slug: "035-miniature-folio", title: "Miniature Folio", family: "Crafts",
    subject: "A fictional illustrated edition of a Persian epic.", format: "editorial", mode: "light",
    thesis: "Persian miniature painting: lapis, vermilion, gold margins",
    fonts: ["Lalezar","Vazirmatn"], swatch: ["#f2e6c9","#1d2a5c","#d2452f","#c49a3a"],
    grammar: "Text panels inside illuminated margins; right-to-left page turn",
    motif: "Gold rule borders with floral illumination",
    status: "planned" },
  { n: 36, slug: "036-shan-shui-scroll", title: "Shan Shui Scroll", family: "Crafts",
    subject: "A fictional mountain-poetry anthology.", format: "editorial", mode: "light",
    thesis: "Chinese ink-wash landscape handscroll",
    fonts: ["Ma Shan Zheng","Noto Serif SC"], swatch: ["#f1ebdd","#1f1f1f","#b8292a","#9aa29a"],
    grammar: "Horizontal handscroll read right to left, one scene at a time",
    motif: "Cinnabar seal stamps and diffused ink washes",
    status: "planned" },
  { n: 37, slug: "037-bojagi-light", title: "Bojagi Light", family: "Crafts",
    subject: "A fictional ramie-textile atelier.", format: "landing", mode: "light",
    thesis: "Korean bojagi: translucent ramie patchwork held up to light",
    fonts: ["Gowun Batang","Gowun Dodum"], swatch: ["#f7f4ec","#4a4a44","#e7b7a3","#a9c3b8"],
    grammar: "Translucent overlapping panels with visible seams",
    motif: "Double-stitched seam lines (ssamsol)",
    status: "planned" },
  { n: 38, slug: "038-azulejo-facade", title: "Azulejo Facade", family: "Crafts",
    subject: "A tile-restoration workshop.", format: "catalog", mode: "light",
    thesis: "Portuguese azulejo: cobalt on tin-white glaze, 14cm tile module",
    fonts: ["Rozha One","Lusitana"], swatch: ["#f8f7f2","#1b3a8a","#6f8fcf","#e3b95a"],
    grammar: "Every panel is a multiple of the square tile module",
    motif: "Hand-painted cobalt tile pattern with crazed glaze",
    status: "planned" },
  { n: 39, slug: "039-scherenschnitt", title: "Scherenschnitt", family: "Crafts",
    subject: "A fictional alpine folk-tale collection.", format: "poster", mode: "light",
    thesis: "Swiss-German papercut: symmetric black silhouettes on cream",
    fonts: ["Pirata One","Alice"], swatch: ["#f4eee1","#111111","#3d6b4a","#d8cdb4"],
    grammar: "Bilateral symmetry about a centre fold; each story is a cut panel",
    motif: "Folded-and-cut symmetric silhouette scenes (SVG)",
    status: "planned" },
  { n: 40, slug: "040-kanga-proverb", title: "Kanga Proverb", family: "Crafts",
    subject: "A fictional East African textile house.", format: "landing", mode: "light",
    thesis: "Swahili kanga cloth: border (pindo), centre (mji), proverb (jina)",
    fonts: ["Rammetto One","Ubuntu"], swatch: ["#fdf6e3","#141414","#e2532b","#1f8a70"],
    grammar: "Every screen is a cloth: border frame, central motif, proverb band",
    motif: "Proverb band in a bold ribbon along the lower edge",
    status: "planned" },
  { n: 41, slug: "041-agitprop-diagonal", title: "Agitprop Diagonal", family: "Eras",
    subject: "A fictional workers' radio station.", format: "poster", mode: "light",
    thesis: "Russian Constructivism: red and black diagonals, photomontage",
    fonts: ["Russo One","Jura"], swatch: ["#efe7d6","#0f0f0f","#d7261e","#9a9a8e"],
    grammar: "All content set on 30 and 60 degree diagonals",
    motif: "Angled type bars and circles that cut the frame",
    status: "planned" },
  { n: 42, slug: "042-nouveau-whiplash", title: "Nouveau Whiplash", family: "Eras",
    subject: "A fictional absinthe-free botanical tonic.", format: "landing", mode: "light",
    thesis: "Art Nouveau: whiplash curves, stylised flora, framed panels",
    fonts: ["Federant","Linden Hill"], swatch: ["#efe4c8","#3d2b1f","#8a9a5b","#c46b4a"],
    grammar: "Tall arched panels with organic frame borders",
    motif: "Whiplash curves drawn as SVG vine borders",
    status: "planned" },
  { n: 43, slug: "043-dessau-lowercase", title: "Dessau Lowercase", family: "Eras",
    subject: "Prospectus for a fictional design school, 1926.", format: "docs", mode: "light",
    thesis: "Bauhaus: lowercase only, primaries, circle square triangle",
    fonts: ["Didact Gothic"], swatch: ["#f1eee6","#111111","#e53222","#1f4fa3"],
    grammar: "Asymmetric grid, heavy bars, all text lowercase",
    motif: "Circle, square and triangle as the only shapes",
    status: "planned" },
  { n: 44, slug: "044-milano-1981", title: "Milano 1981", family: "Eras",
    subject: "A furniture collection from a fictional design collective.", format: "catalog", mode: "light",
    thesis: "Memphis Group era: clashing laminates, squiggles, terrazzo",
    fonts: ["Shrikhand","Darker Grotesque"], swatch: ["#fff0e6","#1a1a1a","#ff5ca8","#1fb3e0"],
    grammar: "Objects on plinths, tilted grids, pattern on every surface",
    motif: "Squiggle and confetti laminate patterns",
    status: "planned" },
  { n: 45, slug: "045-ballroom-1967", title: "Ballroom 1967", family: "Eras",
    subject: "A fictional summer concert series.", format: "poster", mode: "light",
    thesis: "Psychedelic concert poster: melting letterforms, vibrating colours",
    fonts: ["Kablammo","Averia Serif Libre"], swatch: ["#ff6a13","#3b0a45","#1fd1a2","#f9e04b"],
    grammar: "Text distorted to fill organic shapes; complementary colours vibrate",
    motif: "Type that warps along SVG paths",
    status: "planned" },
  { n: 46, slug: "046-aqua-2001", title: "Aqua 2001", family: "Eras",
    subject: "A fictional desktop music player.", format: "app", mode: "light",
    thesis: "Early-2000s glossy gel buttons, pinstripes, brushed metal",
    fonts: ["Varela Round"], swatch: ["#e9eef3","#1c2733","#3a8dde","#b9c3cc"],
    grammar: "Window chrome with a traffic-light titlebar and brushed-metal panels",
    motif: "Glossy gel pill buttons with a specular highlight",
    status: "planned" },
  { n: 47, slug: "047-parole-in-liberta", title: "Parole in Liberta", family: "Eras",
    subject: "A fictional manifesto for speed.", format: "editorial", mode: "light",
    thesis: "Italian Futurism: words set free, typographic explosions",
    fonts: ["Bodoni Moda","League Gothic"], swatch: ["#f2efe6","#121212","#c0392b","#7d7d7d"],
    grammar: "No grid: words radiate from impact points at many sizes",
    motif: "Onomatopoeia set in bursts",
    status: "planned" },
  { n: 48, slug: "048-geocities-1998", title: "Geocities 1998", family: "Eras",
    subject: "A fan page for a fictional sci-fi show.", format: "landing", mode: "light",
    thesis: "Personal homepage 1998: tiled backgrounds, web rings, visitor counter",
    fonts: ["Comic Neue","Tinos"], swatch: ["#000080","#ffff00","#00ff00","#ff00ff"],
    grammar: "Centered table layout, horizontal rules, frames-like side panel",
    motif: "Under-construction strip, visitor counter, web-ring badge",
    status: "planned" },
  { n: 49, slug: "049-wiener-werkstatte", title: "Wiener Werkstatte", family: "Eras",
    subject: "Silver and furniture catalogue of a fictional Vienna workshop, 1905.", format: "catalog", mode: "light",
    thesis: "Vienna Secession: black-and-white checker grid, square forms",
    fonts: ["Federo","Rosarivo"], swatch: ["#faf8f3","#0a0a0a","#bfa76a","#6b6b6b"],
    grammar: "Everything sits in squares; checkerboard borders",
    motif: "Small-square checker border and square monogram",
    status: "planned" },
  { n: 50, slug: "050-lapidary-capitals", title: "Lapidary Capitals", family: "Eras",
    subject: "A fictional museum of Roman inscriptions.", format: "editorial", mode: "light",
    thesis: "Roman carved capitals on marble: serifs from the chisel",
    fonts: ["Cinzel","Castoro"], swatch: ["#ece8e1","#2f2b28","#8b3a2e","#a9a39a"],
    grammar: "Monumental centred inscriptions, text in carved panels",
    motif: "Incised letters (inset shadows) with red-painted grooves",
    status: "planned" },
  { n: 51, slug: "051-ordnance-contours", title: "Ordnance Contours", family: "Nature & Science",
    subject: "A fictional long-distance walking route.", format: "map", mode: "light",
    thesis: "Topographic survey map: contours, hillshade, grid squares",
    fonts: ["Fira Sans Condensed","Merriweather"], swatch: ["#f6f2e4","#5a3e1b","#3a7bbf","#6b8e4e"],
    grammar: "Map fills the viewport; legend and route stages in margin panels",
    motif: "Contour lines with index contours and spot heights",
    status: "planned" },
  { n: 52, slug: "052-nautical-chart", title: "Nautical Chart", family: "Nature & Science",
    subject: "Harbour guide for a fictional sailing school.", format: "map", mode: "light",
    thesis: "Nautical chart: buff land, blue shallows, magenta hazards",
    fonts: ["Saira Condensed","Vollkorn"], swatch: ["#f5ecd0","#1e2b3a","#8ec3e6","#c23b8e"],
    grammar: "Chart with soundings; content sits in a compass rose and notes",
    motif: "Compass rose and depth soundings in italic",
    status: "planned" },
  { n: 53, slug: "053-engraved-star-atlas", title: "Engraved Star Atlas", family: "Nature & Science",
    subject: "A fictional reissue of an 1801 celestial atlas.", format: "catalog", mode: "light",
    thesis: "Copperplate star atlas on cream paper",
    fonts: ["IM Fell English SC","IM Fell English"], swatch: ["#f3ead5","#2d261e","#8a5a2b","#1b3b6f"],
    grammar: "Plate-by-plate constellation charts with coordinate borders",
    motif: "Engraved hatching and coordinate grid ticks",
    status: "planned" },
  { n: 54, slug: "054-crystal-habit", title: "Crystal Habit", family: "Nature & Science",
    subject: "A mineralogy collection database.", format: "specimen", mode: "light",
    thesis: "Crystallography plates: axonometric crystals, Miller indices",
    fonts: ["Spline Sans Mono","Literata"], swatch: ["#f4f6f7","#1d2433","#7a4fd1","#27a38b"],
    grammar: "Crystal drawings on axis crosses; data tables of lattice values",
    motif: "Rotating wireframe crystal (CSS 3D)",
    status: "planned" },
  { n: 55, slug: "055-mycology-field-guide", title: "Mycology Field Guide", family: "Nature & Science",
    subject: "A regional mushroom field guide.", format: "catalog", mode: "light",
    thesis: "Field guide: spore prints, gill diagrams, edibility codes",
    fonts: ["Young Serif","Libre Franklin"], swatch: ["#efe8dc","#3a2c22","#b5552d","#7b8b52"],
    grammar: "Species pages with a key sidebar and spore-print circles",
    motif: "Radial spore prints as section markers",
    status: "planned" },
  { n: 56, slug: "056-abyssal-light", title: "Abyssal Light", family: "Nature & Science",
    subject: "A fictional deep-sea research vessel.", format: "landing", mode: "dark",
    thesis: "Bioluminescence at depth: black water, cold glows",
    fonts: ["Advent Pro","Sarabun"], swatch: ["#02060c","#8fe9ff","#2b6cff","#c46bff"],
    grammar: "Descent by scroll; depth gauge on the side, light sources appear",
    motif: "Drifting bioluminescent particles",
    status: "planned" },
  { n: 57, slug: "057-petri-culture", title: "Petri Culture", family: "Nature & Science",
    subject: "Lab notebook for a fictional microbiology lab.", format: "dashboard", mode: "light",
    thesis: "Agar plates: circular colonies, streak patterns, labels on lids",
    fonts: ["Lexend","Victor Mono"], swatch: ["#f8f2e2","#2a2a2a","#e0a33b","#b93a6b"],
    grammar: "Circular plates as the main containers, not rectangles",
    motif: "Colony growth animation on hover",
    status: "planned" },
  { n: 58, slug: "058-synoptic-chart", title: "Synoptic Chart", family: "Nature & Science",
    subject: "A fictional marine weather service.", format: "map", mode: "light",
    thesis: "Surface weather chart: isobars, fronts, station models",
    fonts: ["Azeret Mono","Sofia Sans Condensed"], swatch: ["#ffffff","#1a1a1a","#d62d20","#2b59c3"],
    grammar: "Chart with fronts drawn over the page; forecasts in station-model glyphs",
    motif: "Cold and warm front lines with triangles and semicircles",
    status: "planned" },
  { n: 59, slug: "059-entomology-drawers", title: "Entomology Drawers", family: "Nature & Science",
    subject: "Collection catalogue of a fictional natural-history museum.", format: "catalog", mode: "light",
    thesis: "Insect specimen drawers: pins, unit trays, tiny labels",
    fonts: ["Gilda Display","Petrona"], swatch: ["#e8dcc3","#2a2016","#7a2e1f","#3f6b4a"],
    grammar: "Glass-topped drawer grid of unit trays",
    motif: "Pinned specimen with a stack of tiny labels on the pin",
    status: "planned" },
  { n: 60, slug: "060-electron-micrograph", title: "Electron Micrograph", family: "Nature & Science",
    subject: "A pollen-grain image library.", format: "specimen", mode: "dark",
    thesis: "SEM micrographs: greyscale relief, scale bars, data strip",
    fonts: ["Hanken Grotesk","Major Mono Display"], swatch: ["#0c0c0c","#e6e6e6","#6f6f6f","#39ff88"],
    grammar: "Full-bleed grey images with instrument data strip along the bottom",
    motif: "Scale bar with magnification and kV readout",
    status: "planned" },
  { n: 61, slug: "061-letterpress-cotton", title: "Letterpress Cotton", family: "Material & Surface",
    subject: "A fictional wedding-stationery press.", format: "specimen", mode: "light",
    thesis: "Deep letterpress impression on thick cotton paper",
    fonts: ["Abril Fatface","Rufina"], swatch: ["#f7f3ea","#16233d","#d9534f","#c7bfae"],
    grammar: "Centred compositions with generous margins; type debossed",
    motif: "Deep deboss (inset shadows) and uneven ink coverage",
    status: "planned" },
  { n: 62, slug: "062-night-neon", title: "Night Neon", family: "Material & Surface",
    subject: "A fictional neon-sign workshop.", format: "landing", mode: "dark",
    thesis: "Bent glass neon on brick at night",
    fonts: ["Yellowtail","Monoton"], swatch: ["#1a1413","#ff4fd8","#3dfff2","#ff9b3d"],
    grammar: "Signs mounted on a brick wall; each section is a sign",
    motif: "Tube flicker on load and visible mounting brackets",
    status: "planned" },
  { n: 63, slug: "063-anodized-nameplate", title: "Anodized Nameplate", family: "Material & Surface",
    subject: "Component catalogue for a fictional test-equipment maker.", format: "specimen", mode: "light",
    thesis: "Engraved anodised aluminium plates and brushed steel",
    fonts: ["Michroma","Tomorrow"], swatch: ["#c8ccd0","#1b1e22","#2f6db3","#c0392b"],
    grammar: "Panels screwed to a steel surface; labels engraved",
    motif: "Screw heads and brushed-metal texture",
    status: "planned" },
  { n: 64, slug: "064-chancery-seal", title: "Chancery Seal", family: "Material & Surface",
    subject: "A fictional land-grant charter.", format: "editorial", mode: "light",
    thesis: "Chancery document: vellum, calligraphy, red wax seal, ribbon",
    fonts: ["Pinyon Script","Radley"], swatch: ["#f1e7d0","#2a2320","#9e1b1b","#6b5a3c"],
    grammar: "One long charter with ruled margins; seal at the foot",
    motif: "Pressed wax seal with a ribbon",
    status: "planned" },
  { n: 65, slug: "065-felt-board", title: "Felt Board", family: "Material & Surface",
    subject: "A kindergarten storytime planner.", format: "app", mode: "light",
    thesis: "Felt cut-outs on a felt board",
    fonts: ["Fredoka","Sniglet"], swatch: ["#3b7d4f","#fff7e8","#ffb3c1","#ffd23f"],
    grammar: "Soft shapes placed on the board; drag to rearrange",
    motif: "Fuzzy felt edge texture (SVG turbulence)",
    status: "planned" },
  { n: 66, slug: "066-celadon-glaze", title: "Celadon Glaze", family: "Material & Surface",
    subject: "A fictional ceramics studio.", format: "landing", mode: "light",
    thesis: "Goryeo celadon: jade-green glaze, crackle, inlaid white",
    fonts: ["Hahmlet","Gothic A1"], swatch: ["#dfe8df","#26352d","#8fb29a","#f6f3ea"],
    grammar: "Rounded vessel silhouettes contain content",
    motif: "Fine crackle network drawn over the glaze",
    status: "planned" },
  { n: 67, slug: "067-marquetry-inlay", title: "Marquetry Inlay", family: "Material & Surface",
    subject: "A fictional furniture restorer.", format: "catalog", mode: "light",
    thesis: "Wood marquetry: contrasting veneers, parquet geometry",
    fonts: ["Forum","Proza Libre"], swatch: ["#b07a4a","#2b1a10","#e9d3b0","#5a3620"],
    grammar: "Content inlaid into veneer panels with stringing lines",
    motif: "Parquet and banding patterns in several woods",
    status: "planned" },
  { n: 68, slug: "068-gold-tooled-binding", title: "Gold-Tooled Binding", family: "Material & Surface",
    subject: "A fictional private-press library.", format: "landing", mode: "dark",
    thesis: "Leather bookbinding with gold tooling and marbled endpapers",
    fonts: ["Almendra Display","Goudy Bookletter 1911"], swatch: ["#3a1e14","#e8c77a","#6e2a1a","#274a3c"],
    grammar: "Book spines and boards; opening a book shows marbled endpapers",
    motif: "Blind and gold-tooled ornament frames",
    status: "planned" },
  { n: 69, slug: "069-school-chalkboard", title: "School Chalkboard", family: "Material & Surface",
    subject: "A fictional physics lesson on pendulums.", format: "docs", mode: "dark",
    thesis: "Slate chalkboard with chalk dust and erased ghosts",
    fonts: ["Cabin Sketch","Gochi Hand"], swatch: ["#2c3a33","#f1f1ea","#f6d365","#9fd3c7"],
    grammar: "Lesson written across the board; diagrams sketched in chalk",
    motif: "Chalk-smear ghosts of previous lessons",
    status: "planned" },
  { n: 70, slug: "070-sampler-stitch", title: "Sampler Stitch", family: "Material & Surface",
    subject: "A fictional needlework guild.", format: "poster", mode: "light",
    thesis: "Cross-stitch sampler on linen: alphabet rows, border, motto",
    fonts: ["Handjet","Nunito"], swatch: ["#efe6d6","#27413a","#b3413b","#d8a24a"],
    grammar: "Every element is on a stitch grid; alphabet rows and a motto",
    motif: "Cross-stitch X marks at every cell",
    status: "planned" },
  { n: 71, slug: "071-terminal-wayfinding", title: "Terminal Wayfinding", family: "Systems & Signage",
    subject: "Wayfinding for a fictional international airport.", format: "tool", mode: "dark",
    thesis: "Airport signage: yellow on dark grey, pictograms, gate numbers",
    fonts: ["Signika"], swatch: ["#2b2d2f","#ffd100","#ffffff","#4a4d50"],
    grammar: "Sign modules with arrows; everything reads at a distance",
    motif: "Directional pictograms and arrow chevrons",
    status: "planned" },
  { n: 72, slug: "072-interstate-signage", title: "Interstate Signage", family: "Systems & Signage",
    subject: "A fictional cross-country road trip.", format: "landing", mode: "light",
    thesis: "Highway signage: green panels, white reflective letters, shields",
    fonts: ["Overpass","Overpass Mono"], swatch: ["#dfe3e0","#0b6b3a","#ffffff","#1f4d9b"],
    grammar: "Overhead sign gantries as section headers; mile markers as progress",
    motif: "Route shield badges and exit tabs",
    status: "planned" },
  { n: 73, slug: "073-signal-flags", title: "Signal Flags", family: "Systems & Signage",
    subject: "A fictional yacht club regatta app.", format: "app", mode: "light",
    thesis: "International maritime signal flags as the alphabet of the UI",
    fonts: ["Teko","Heebo"], swatch: ["#f5f5f0","#0a1f44","#e31b23","#ffd200"],
    grammar: "Flag hoists spell section names; navigation is a flag line",
    motif: "Signal-flag glyphs built from rectangles and triangles",
    status: "planned" },
  { n: 74, slug: "074-transit-diagram", title: "Transit Diagram", family: "Systems & Signage",
    subject: "A fictional city's metro network.", format: "map", mode: "light",
    thesis: "Octilinear transit diagram: 45 and 90 degree lines, tick stations",
    fonts: ["Encode Sans"], swatch: ["#eef0f2","#22313f","#00843d","#a05eb5"],
    grammar: "The diagram is the page; stations open detail panels",
    motif: "Interchange roundels and line colours",
    status: "planned" },
  { n: 75, slug: "075-engraved-score", title: "Engraved Score", family: "Systems & Signage",
    subject: "A fictional string-quartet premiere programme.", format: "editorial", mode: "light",
    thesis: "Engraved music notation: staves, clefs, dynamics",
    fonts: ["Libre Caslon Display","Noto Music"], swatch: ["#fbfaf6","#141414","#9c2f2f","#8f8a80"],
    grammar: "Content laid on five-line staves; sections as movements",
    motif: "Staves, bar lines and dynamics marks",
    status: "planned" },
  { n: 76, slug: "076-labanotation", title: "Labanotation", family: "Systems & Signage",
    subject: "A fictional dance-archive score.", format: "docs", mode: "light",
    thesis: "Laban movement notation: vertical staff read bottom to top",
    fonts: ["Commissioner"], swatch: ["#ecefe9","#161616","#5b3fc4","#d7c9a8"],
    grammar: "Vertical staff columns, reading from the bottom",
    motif: "Direction symbols with shading for level",
    status: "planned" },
  { n: 77, slug: "077-paint-fan-deck", title: "Paint Fan Deck", family: "Systems & Signage",
    subject: "Colour picker for a fictional paint maker.", format: "tool", mode: "light",
    thesis: "Paint-chip fan deck: strips of chips that fan open",
    fonts: ["Belleza","Albert Sans"], swatch: ["#fafafa","#202020","#6a8caf","#d17a5c"],
    grammar: "Strips pivot from one rivet; selected strip expands",
    motif: "Fan-out rotation around a single brass rivet",
    status: "planned" },
  { n: 78, slug: "078-film-call-sheet", title: "Film Call Sheet", family: "Systems & Signage",
    subject: "Call sheet for a fictional indie film shoot.", format: "tool", mode: "light",
    thesis: "Production paperwork: call sheet, clapperboard, scene numbers",
    fonts: ["Courier Prime","Oswald"], swatch: ["#fcfcf7","#111111","#f2c200","#4a6fa5"],
    grammar: "Dense form grid with boxed fields; clapperboard header",
    motif: "Clapperboard stripes and slate numbers",
    status: "planned" },
  { n: 79, slug: "079-philately-sheet", title: "Philately Sheet", family: "Systems & Signage",
    subject: "A fictional stamp-collectors' society.", format: "catalog", mode: "light",
    thesis: "Postage stamps: perforations, engraving, cancellation marks",
    fonts: ["Libre Bodoni","Stint Ultra Expanded"], swatch: ["#efeae0","#2a2a2a","#b03a2e","#2e5e4e"],
    grammar: "Stamps in album mounts on quad-ruled album pages",
    motif: "Perforated edges (radial-gradient masks) and wavy cancellations",
    status: "planned" },
  { n: 80, slug: "080-reykjavik-1972", title: "Reykjavik 1972", family: "Systems & Signage",
    subject: "Replay site for a fictional chess championship.", format: "dashboard", mode: "light",
    thesis: "Chess tournament: scoresheets, algebraic notation, clocks",
    fonts: ["Domine","Noto Sans Symbols 2"], swatch: ["#f0ece3","#1e1e1e","#7a5230","#c7b299"],
    grammar: "Board at centre, scoresheet and analogue clocks at the sides",
    motif: "Chess clock with flag and algebraic move list",
    status: "planned" },
  { n: 81, slug: "081-pinball-backglass", title: "Pinball Backglass", family: "Play",
    subject: "A fictional 1978 pinball machine.", format: "landing", mode: "dark",
    thesis: "Pinball backglass art: reverse-painted glass, score reels",
    fonts: ["Faster One","Bowlby One"], swatch: ["#140a2e","#ff2e6a","#ffd23f","#20c4ff"],
    grammar: "Backglass hero with score reels; playfield lamps as navigation",
    motif: "Chasing light bulbs and mechanical score reels",
    status: "planned" },
  { n: 82, slug: "082-holo-trading-card", title: "Holo Trading Card", family: "Play",
    subject: "A fictional creature card game.", format: "catalog", mode: "dark",
    thesis: "Holographic foil trading cards with rarity tiers",
    fonts: ["Alfa Slab One","Mada"], swatch: ["#0e2a2f","#f2f2f2","#9d7bff","#ff7ac8"],
    grammar: "Cards in binder pages; one card lifts and tilts to the cursor",
    motif: "Holo foil sheen tied to pointer angle",
    status: "planned" },
  { n: 83, slug: "083-benday-comic", title: "Ben-Day Comic", family: "Play",
    subject: "A fictional comic-shop newsletter.", format: "editorial", mode: "light",
    thesis: "Silver-age comic printing: Ben-Day dots, CMYK, speech balloons",
    fonts: ["Bangers","Patrick Hand"], swatch: ["#fff7d6","#111111","#e2231a","#00a0dc"],
    grammar: "Panels in a page gutter grid; captions in yellow boxes",
    motif: "Ben-Day dot fills and burst balloons",
    status: "planned" },
  { n: 84, slug: "084-tin-robot-box", title: "Tin Robot Box", family: "Play",
    subject: "Reissue of a fictional 1960s Japanese tin toy robot.", format: "landing", mode: "light",
    thesis: "Tin-toy box art: lithographed tin, bold katakana, action poses",
    fonts: ["Dela Gothic One","Kosugi"], swatch: ["#e9dcc0","#1c2b4a","#e63b2e","#f2b705"],
    grammar: "Box panels (front, side, top) as the page structure",
    motif: "Lithographed tin texture and wind-up key",
    status: "planned" },
  { n: 85, slug: "085-chromolitho-circus", title: "Chromolitho Circus", family: "Play",
    subject: "A fictional travelling circus season.", format: "poster", mode: "light",
    thesis: "Victorian chromolithograph circus poster",
    fonts: ["Rye","Glass Antiqua"], swatch: ["#f6e8c3","#2b1b12","#c1272d","#1f5f8b"],
    grammar: "Stacked banner lines of changing type; ornate frames",
    motif: "Ribbon banners and star bursts",
    status: "planned" },
  { n: 86, slug: "086-claymation-studio", title: "Claymation Studio", family: "Play",
    subject: "A fictional stop-motion animation studio.", format: "landing", mode: "light",
    thesis: "Plasticine: soft, thumb-printed shapes, stepped 12fps motion",
    fonts: ["Chewy","Baloo 2"], swatch: ["#ffe7c2","#3b2a20","#ff7a59","#5bc0be"],
    grammar: "Lumpy blob containers; motion stepped at 12 frames per second",
    motif: "Thumbprint texture and steps() animation",
    status: "planned" },
  { n: 87, slug: "087-rainbow-stationery", title: "Rainbow Stationery", family: "Play",
    subject: "A fictional 1990s school-supply catalogue.", format: "landing", mode: "light",
    thesis: "90s rainbow stationery: gradient animals, stickers, glitter",
    fonts: ["Grandstander","Mali"], swatch: ["#fff5fb","#3a1d5c","#ff4fa3","#34d1bf"],
    grammar: "Sticker sheets and trapper-keeper panels",
    motif: "Puffy stickers and rainbow gradients",
    status: "planned" },
  { n: 88, slug: "088-skate-deck-1987", title: "Skate Deck 1987", family: "Play",
    subject: "A fictional skate company's deck lineup.", format: "catalog", mode: "dark",
    thesis: "Late-80s skateboard graphics: screen-printed, gnarly",
    fonts: ["Metal Mania","Permanent Marker"], swatch: ["#101010","#f4f1e8","#8cff00","#ff2f92"],
    grammar: "Vertical deck shapes lined up; grip-tape texture",
    motif: "Screen-print registration and grip-tape grain",
    status: "planned" },
  { n: 89, slug: "089-parlour-board-game", title: "Parlour Board Game", family: "Play",
    subject: "A fictional family board game from 1962.", format: "app", mode: "light",
    thesis: "Mid-century board game: track board, dice, tokens",
    fonts: ["Holtwood One SC","Arbutus Slab"], swatch: ["#f2e6c9","#2a2a2a","#d9412b","#2c7a4b"],
    grammar: "The board track is the navigation; sections are board spaces",
    motif: "Dice that roll to a random section",
    status: "planned" },
  { n: 90, slug: "090-gouache-picture-book", title: "Gouache Picture Book", family: "Play",
    subject: "A fictional children's picture book.", format: "editorial", mode: "light",
    thesis: "Hand-painted gouache: flat opaque colour, visible brush edges",
    fonts: ["Gluten","Andika"], swatch: ["#fbf3e4","#35302b","#e4775a","#6aa6a0"],
    grammar: "Double-page spreads that turn",
    motif: "Opaque brushy shapes with dry-brush edges",
    status: "planned" },
  { n: 91, slug: "091-kinetic-variable", title: "Kinetic Variable", family: "Experimental",
    subject: "A fictional type conference.", format: "poster", mode: "light",
    thesis: "Only type: one variable font animated on width and weight axes",
    fonts: ["Anybody"], swatch: ["#f0f0e8","#0e0e0e","#0e0e0e","#f0f0e8"],
    grammar: "No images and no boxes; type is the layout",
    motif: "Letterforms that stretch with scroll velocity",
    status: "planned" },
  { n: 92, slug: "092-one-bit-desktop", title: "One-Bit Desktop", family: "Experimental",
    subject: "A fictional 1984 word-processor.", format: "app", mode: "light",
    thesis: "1-bit display: black and white only, dithered greys, 512x342",
    fonts: ["Silkscreen","Jersey 10"], swatch: ["#ffffff","#000000","#000000","#ffffff"],
    grammar: "Windows, menu bar and dithered patterns on a fixed small screen",
    motif: "Dither patterns in place of every grey",
    status: "planned" },
  { n: 93, slug: "093-ascii-only", title: "ASCII Only", family: "Experimental",
    subject: "Documentation for a fictional command-line tool.", format: "docs", mode: "dark",
    thesis: "Every visual element is drawn with ASCII characters",
    fonts: ["Inconsolata"], swatch: ["#0d0d0d","#d0d0d0","#ffb86b","#6b6b6b"],
    grammar: "Box-drawn panels, ASCII tables and diagrams; no CSS borders",
    motif: "ASCII art diagrams and figlet-style headings",
    status: "planned" },
  { n: 94, slug: "094-single-hue", title: "Single Hue", family: "Experimental",
    subject: "A fictional citrus farm.", format: "landing", mode: "light",
    thesis: "One hue only: every colour is a tint or shade of one orange",
    fonts: ["Archivo"], swatch: ["#fff3e8","#4a1d00","#ff6a00","#ffb27a"],
    grammar: "Colour does all the hierarchy; no second hue",
    motif: "Tonal bands from darkest to lightest",
    status: "planned" },
  { n: 95, slug: "095-raw-html", title: "Raw HTML", family: "Experimental",
    subject: "A fictional personal essay archive.", format: "editorial", mode: "light",
    thesis: "Browser defaults as a style: Times, blue links, grey buttons",
    fonts: ["browser default serif"], swatch: ["#ffffff","#000000","#0000ee","#551a8b"],
    grammar: "Semantic HTML with minimal CSS; pure document flow",
    motif: "Visited-link purple and default form controls",
    status: "planned" },
  { n: 96, slug: "096-corridor-3d", title: "Corridor 3D", family: "Experimental",
    subject: "A fictional virtual art gallery.", format: "landing", mode: "dark",
    thesis: "CSS 3D perspective: a corridor you move through by scrolling",
    fonts: ["Unica One","Mukta"], swatch: ["#0b0b10","#f5f5f5","#ff5b3a","#3a3a4a"],
    grammar: "Walls, floor and ceiling built with CSS 3D; scroll moves the camera",
    motif: "Paintings that turn to face the viewer",
    status: "planned" },
  { n: 97, slug: "097-lipogram", title: "Lipogram", family: "Experimental",
    subject: "A fictional literary magazine.", format: "editorial", mode: "light",
    thesis: "Oulipo constraint: no letter 'e' in any visible text",
    fonts: ["Gloock","Schibsted Grotesk"], swatch: ["#e8eef5","#1c1c1c","#d1495b","#8aa1b8"],
    grammar: "Classic magazine layout; an 'e' counter reads zero",
    motif: "A struck-through 'e' as the only ornament",
    status: "planned" },
  { n: 98, slug: "098-marseille-tarot", title: "Marseille Tarot", family: "Experimental",
    subject: "A fictional tarot deck reissue.", format: "catalog", mode: "light",
    thesis: "Woodcut tarot: flat stencil colours on cream, black outlines",
    fonts: ["Grenze Gotisch","Grenze"], swatch: ["#f3e6c8","#161616","#2a5fb0","#e4b100"],
    grammar: "Card layout with titled banners top and bottom",
    motif: "Stencil colour fills slightly out of register",
    status: "planned" },
  { n: 99, slug: "099-solarpunk-coop", title: "Solarpunk Co-op", family: "Experimental",
    subject: "Energy dashboard for a fictional housing co-op.", format: "dashboard", mode: "light",
    thesis: "Hopeful solarpunk: greenery, solar panels, hand-drawn warmth",
    fonts: ["Bricolage Grotesque","Source Serif 4"], swatch: ["#f4f7ea","#1f3a2e","#f2b134","#5aa469"],
    grammar: "Garden-bed grid of tiles; plants grow as values increase",
    motif: "Hand-drawn leaves that grow with data",
    status: "planned" },
  { n: 100, slug: "100-sundial-hours", title: "Sundial Hours", family: "Experimental",
    subject: "A fictional astronomical clock museum.", format: "landing", mode: "light",
    thesis: "Time-driven: palette and shadows follow the viewer's local hour",
    fonts: ["Philosopher","Nunito Sans"], swatch: ["#f7efe0","#2a2530","#e28f3a","#324b7a"],
    grammar: "Gnomon shadow crosses the page; sections are the hours",
    motif: "Shadow angle and palette computed from the local time",
    status: "planned" },
];
